#!/bin/bash
# music push
for ((;;))
do
if [ $(mocp -Q %state) == "PLAY" ]
then
  wget -q -O - "http://domain.com/random.php?music=$(mocp -Q %title | sed "s/&/and/")" 
  else 
 wget -q -O - http://domain.com/random.php?music=" "
fi
sleep 3s
done


