#!/bin/bash
# music push?
for ((;;))
do
if [ "$(pidof mocp)" ]
then
  wget -q -O - "http://store.wuxmedia.com/aeB3yoht.php?music=$(mocp -Q %title | sed "s/&/and/")" 
  else 
 wget -q -O - http://store.wuxmedia.com/aeB3yoht.php?music=" "
fi
sleep 3s
done


